// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtmBe4o5JWdS4kYEt89m6gdf2WTGrD-Y',
    appId: '1:802048372343:web:f7e73c04ebca46794a2072',
    messagingSenderId: '802048372343',
    projectId: 'pato-burguer-73412',
    authDomain: 'pato-burguer-73412.firebaseapp.com',
    databaseURL: 'https://pato-burguer-73412-default-rtdb.firebaseio.com',
    storageBucket: 'pato-burguer-73412.appspot.com',
    measurementId: 'G-FK4NR63VZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Ji2xnHvnab3LkmA5TMLj8U7darY6WSA',
    appId: '1:802048372343:android:cb28fb05a5d183fb4a2072',
    messagingSenderId: '802048372343',
    projectId: 'pato-burguer-73412',
    databaseURL: 'https://pato-burguer-73412-default-rtdb.firebaseio.com',
    storageBucket: 'pato-burguer-73412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONOlJet64IUKfORjsb6RHGAsWUk6vBOQ',
    appId: '1:802048372343:ios:8fad854c05695dd24a2072',
    messagingSenderId: '802048372343',
    projectId: 'pato-burguer-73412',
    databaseURL: 'https://pato-burguer-73412-default-rtdb.firebaseio.com',
    storageBucket: 'pato-burguer-73412.appspot.com',
    iosClientId: '802048372343-lltqfh8i207d8uuj2dhqmka9t15r5i71.apps.googleusercontent.com',
    iosBundleId: 'com.example.patoBurguerClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAONOlJet64IUKfORjsb6RHGAsWUk6vBOQ',
    appId: '1:802048372343:ios:18b96062ed02ae354a2072',
    messagingSenderId: '802048372343',
    projectId: 'pato-burguer-73412',
    databaseURL: 'https://pato-burguer-73412-default-rtdb.firebaseio.com',
    storageBucket: 'pato-burguer-73412.appspot.com',
    iosClientId: '802048372343-lj9cp95r990lpcccfopi5o4iqnfc7t3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.patoBurguerClient.RunnerTests',
  );
}
